# Generated by Django 3.2.20 on 2023-08-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infosec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.CharField(default='abu@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
